# codecov:
#   require_ci_to_pass: true

coverage:
  status:
    project:
      default: off
      dbadmin:
        flags:
          - dbadmin
          - pkg
      envoyauth:
        flags:
          - envoyauth
          - pkg
      envoycp:
        flags:
          - envoycp
          - pkg

flags:
  dbadmin:
    paths:
      - cmd/dbadmin/
  envoyauth:
    paths:
      - cmd/frontend/
  envoycp:
    paths:
      - cmd/envoycp/
  pkg:
    paths:
      - pkg/
